config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Index Page (aka Root)
  root to: 'chapters#index2'

  # Show All Chapters
  get 'chapters/all', to: 'chapters#index'
  # Show Chapter by ID
  get 'chapter/:id', to: 'chapters#show', as: 'chapter'

  # Show All Articles
  get 'articles/all', to: 'articles#index'
  # Show Article by ID
  # get 'article/:id', to: 'articles#show', as: 'article'
  resources :article
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :chapter

  # scope :published, -> {where(published_at: nil)}
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  has_many :articles

  belongs_to :parent, class_name: 'Chapter', foreign_key: :parent_id, optional: true
  has_many   :children, class_name: 'Chapter', foreign_key: :parent_id, inverse_of: :parent

  # Define a scope for the research. It automatically creates a Class.method
  scope :parents_only, -> { where(parent_id: nil) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  # before_action :fetch_article

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  # private
  #   def fetch_article
  #     @articles = Article.published.find(params[:id])
  #   end

end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController

    def index
      @chapters = Chapter.all
      @parent_chapters = Chapter.parent_only
      @articles = Article.all
    end

    def index2
      @chapters = Chapter.parents_only
    end

    def show
      @chapters = Chapter.all
      @chapter = Chapter.find(params[:id])
      @articles = Article.all
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def sexy_date(date)
    return date.strftime("%d/%m/%Y")
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/articles/_article.html.erb
<article>
  <p><%= article.content[0..100]%></p>
  <p>
    <strong>Article: <%= article.title %></strong>
    <em>Created at: <%= sexy_date article.created_at%>
    (<%= distance_of_time_in_words_to_now(article.created_at, include_seconds: true) %>)
    </em>
  </p>
</article>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<section class="articles">
  <% @articles.each do |article| %>
    <article>
      <p><%= article.content[0..255] %></p>
    </article>
  <% end %>
</section>

app/views/articles/show.html.erb
<h1>Article <%= @article.id %></h1>
<p><%= @article.content %></p>

app/views/chapters/_chapter.html.erb
<div class="chapter chapter-<%= chapter.id %>">
  <h1><%= chapter.title %></h1>
  <%= render partial: "sub_chapter", collection: chapter.children, as: :chapter %>
</div>

app/views/chapters/_sub_chapter.html.erb
<div class="sub_chapter sub_chapter-<%= chapter.id %>">
  <h2><%= chapter.title %></h2>
  <%= render chapter.articles %>
</div>

app/views/chapters/index.html.erb
<section class="chapters">
  <!-- Parent Chapter Loop -->
  <% @chapters.each do |chapter| %>
    <% if !chapter.parent_id %>
    <div class="chapter-<%= chapter.id %>">
      <h2><%= chapter.title %>, ID:<%= chapter.id %></h2>

      <!-- Children Chapter Loop -->
      <% chapter.children.each do |sub_chapter| %>
        <h3><%= sub_chapter.title %>, ID: <%= sub_chapter.id %></h3>

        <% @articles.where(:chapter_id => sub_chapter.id).each do |article| %>
          <article>
            <p><%= article.content[0..255] %></p>
          </article>
        <% end %>

      <% end %>

    </div>
    <% end %>
	<% end %>
</section>

app/views/chapters/index2.html.erb
<section class="chapters">
  <%= render @chapters %>
</section>

app/views/chapters/show.html.erb
<h1><%= @chapter.title %></h1>

  <% if !@chapter.parent_id %>
  <h2>Sub-Chapters</h2>
    <ul>
      <% @chapter.children.each do |sub_chapter| %>
        <li><%= link_to sub_chapter.title, chapter_path(Chapter.find(sub_chapter.id)) %></li>
      <% end %>
    </ul>
  <% end %>

  <% if @articles.where(:chapter_id => @chapter.id) %>
    <ul>
      <% @articles.where(:chapter_id => @chapter.id).each do |article| %>
        <li><%= link_to article.content[0..30], article_path(article.id) %></li>
      <% end %>
    </ul>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLab</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>